# -*- coding: utf-8 -*-
"""techinical_test.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QklTWulIQGMRtfuH_gp_SPjF0IN8QiRS

# 🚀 Case Técnico | Cientista de Dados - Galaxies

## 🪐 Contexto
- Base de consumidores com dados **demográficos, surveys e histórico de compras**.  
- Objetivo: **segmentação via clusterização** para gerar **insights de negócio**.

## 📚 Bibliotecas utilizadas
As seguintes bibliotecas foram utilizadas ao longo do projeto:

- **pandas (pd)**: manipulação de dados em tabelas (DataFrames).  
- **numpy (np)**: operações matemáticas e vetoriais de alto desempenho.  
- **StandardScaler**: padronização dos dados, ajustando para média 0 e desvio padrão 1.  
- **PCA**: redução de dimensionalidade, mantendo a maior parte da variância dos dados.  
- **KMeans**: algoritmo de clusterização utilizado para segmentar os clientes.  
- **silhouette_score** e **cotovelo**: métricas para avaliar a qualidade dos clusters formados.  
- **matplotlib.pyplot (plt)**: criação de gráficos.  
- **seaborn (sns)**: visualizações estatísticas mais claras e atrativas, baseada no matplotlib.  
- **datetime**: manipulação de datas, como o cálculo de idade a partir da data de nascimento.
"""

import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score, davies_bouldin_score
import matplotlib.pyplot as plt
import seaborn as sns
from datetime import datetime
from sklearn.metrics import silhouette_score
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler

"""## 🔹 Carregamento e Exploração Inicial da Base

A base de dados foi carregada em um DataFrame com `pandas`.  
Na sequência, foram aplicados comandos de exploração inicial:

- `head()` → visualiza as primeiras linhas da base para conferir a estrutura.  
- `info()` → exibe os tipos de dados de cada coluna e a presença de valores nulos.  
- `describe()` → gera estatísticas descritivas básicas (média, desvio padrão, quartis, mínimos e máximos) para as variáveis numéricas.  

Esses passos iniciais são fundamentais para validar a integridade e compreender a natureza dos dados antes do pré-processamento.

"""

# Ler a base de dados
df = pd.read_csv('dados_sinteticos.csv')

df.head()

df.info() #validar data types e informaçoes de dados nullos

df.describe()

"""## 🔹 Limpeza de Dados Categóricos

Foi realizada uma limpeza simples diretamente no DataFrame para padronizar as variáveis categóricas:

- Conversão para **minúsculas** (`lower`)  
- Remoção de **espaços extras** nas pontas (`strip`)  

Em seguida, foi calculada a **cardinalidade** (número de valores distintos) de cada coluna para identificar variáveis de alta diversidade e avaliar quais poderiam exigir tratamento específico (ex.: agrupamento ou encoding alternativo).

"""

# Limpeza simples direto no dataframe
categorical_cols = df.select_dtypes(include=['object']).columns.tolist()

for col in categorical_cols:
    df[col] = (df[col]
                 .astype(str)
                 .str.lower()                 # minúsculas
                 .str.strip()                 # remove espaços extras nas pontas
              )

# Agora sim calcular cardinalidade
distinct_counts = df.nunique().reset_index()
distinct_counts.columns = ["coluna", "num_valores_distintos"]
print(distinct_counts)

"""## 🔹 Criação da Variável de Idade

A coluna `data_nascimento` foi convertida para o formato datetime e utilizada para calcular a idade de cada cliente.  
A operação consistiu em subtrair o ano de nascimento do ano atual, resultando em uma nova coluna `idade`.

Após a criação da variável, foram exibidas estatísticas descritivas (`describe()`) e informações de tipo de dado (`info()`) para validar o cálculo e garantir que não houve inconsistências.

Esse passo transforma uma informação bruta (data) em uma variável numérica contínua, mais adequada para análises estatísticas e clusterização.

"""

# Converter data de nascimento para datetime
hoje = datetime.now()

df['idade'] = hoje.year - pd.to_datetime(df['data_nascimento'], format='%d/%m/%Y').dt.year

# Exibir estatísticas da idade
df['idade'].describe()

# Exibir estatísticas da idade
df['idade'].info()

"""## 🔹 Criação de Faixas Etárias

A variável `idade` foi transformada em **faixas etárias** por meio de `qcut`, que divide a distribuição em quatro quantis.  
Cada faixa representa 25% da amostra, permitindo comparar grupos etários de forma equilibrada.  

Em seguida, os intervalos gerados (objetos do tipo *Interval*) foram convertidos para **string**, facilitando sua manipulação e posterior transformação em variáveis dummy.  

Essa segmentação torna a análise mais interpretável, permitindo identificar padrões de comportamento por grupo etário.

"""

# Criar faixas etárias em 4 quantis
df['faixa_etaria'] = pd.qcut(df['idade'], q=4)

# Converter de Interval para string (ex.: "(17.999, 31.0]")
df['faixa_etaria'] = df['faixa_etaria'].astype(str)

# Conferir resultado
print(df['faixa_etaria'].value_counts())

"""## 🔹 Criação da Variável Ordinal de Frequência de Compra

A coluna `frequencia_compra` foi convertida em uma variável numérica ordinal (`frequencia_compra_ord`) por meio de um mapeamento personalizado:

- semanal = 0  
- quinzenal = 1  
- mensal = 2  
- bimestral = 3  
- trimestral = 4  

Essa transformação garante que a variável preserve a **ordem natural da frequência** (do mais recorrente para o menos recorrente), permitindo que algoritmos como PCA e KMeans interpretem a informação de forma adequada.

"""

# Mapeamento ordinal personalizado
freq_map = {'semanal':0, 'quinzenal':1, 'mensal':2, 'bimestral':3, 'trimestral':4}
df['frequencia_compra_ord'] = df['frequencia_compra'].map(freq_map)

"""## 🔹 Conversão Final em Variáveis Numéricas

Todas as colunas categóricas restantes foram convertidas em variáveis dummy (0/1) com `get_dummies`, garantindo que a base final ficasse totalmente numérica.  
Além disso, valores nulos foram tratados com `fillna(0)`, assegurando que não houvesse registros inválidos que pudessem comprometer o PCA ou os algoritmos de clusterização.

"""

# Converter todas as colunas categóricas restantes em variáveis dummy (0/1)
df_ready = pd.get_dummies(df, drop_first=True)

# Verificar e remover valores nulos (caso existam)
df_ready = df_ready.fillna(0)

"""## 🔹 Padronização dos Dados

Os dados foram padronizados com `StandardScaler`, ajustando todas as variáveis para média 0 e desvio padrão 1.  
Esse passo é essencial para que nenhuma variável tenha peso desproporcional no cálculo de distâncias, garantindo que o PCA e o KMeans considerem todas as features de forma equilibrada.

"""

scaler = StandardScaler()
X_scaled = scaler.fit_transform(df_ready)

"""## 🔹 Distribuições"""

plt.figure(figsize=(6,4))
plt.hist(df['frequencia_compra'], bins=15, color='skyblue', edgecolor='black')
plt.title('Distribuição de Frequência de compra')
plt.xlabel('frequencia_compra')
plt.ylabel('Contagem')
plt.tight_layout()
plt.show()

plt.figure(figsize=(6,4))
plt.hist(df['faixa_etaria'], bins=15, color='skyblue', edgecolor='black')
plt.title('Distribuição de Idade dos Clientes')
plt.xlabel('Idade (anos)')
plt.ylabel('Contagem')
plt.tight_layout()
plt.show()

plt.figure(figsize=(6,4))
sns.countplot(x='genero', data=df, palette='pastel')
plt.title('Contagem por Gênero')
plt.xlabel('Gênero')
plt.ylabel('Contagem')
plt.tight_layout()
plt.show()

plt.figure(figsize=(6,4))
sns.countplot(x='regiao', data=df, palette='pastel')
plt.title('Contagem por Região')
plt.xlabel('Região')
plt.ylabel('Contagem')
plt.tight_layout()
plt.show()

plt.figure(figsize=(6,4))
sns.boxplot(x=df['ticket_medio'], color='lightgreen')
plt.title('Boxplot do Ticket Médio')
plt.xlabel('Ticket Médio')
plt.tight_layout()
plt.show()

"""### Clusterização

## 🔹 Tratamento de Dados Categóricos

Uma das principais variáveis de alta cardinalidade na base é `influenciador`.  
Ao invés de aplicar **One Hot Encoding** (que criaria milhares de colunas e dificultaria a clusterização), adotamos **Frequency Encoding**.
"""

df['influenciador'] = df['influenciador'].map(df['influenciador'].value_counts(normalize=True))
df = df.drop('influenciador', axis=1)

df_original = df.copy()

display(df_original.head())

"""## 🔹 Preparação da Base

As variáveis categóricas foram convertidas em dummies (0/1) e as numéricas mantidas no formato original.  
Esse passo garante que toda a base esteja em formato numérico, requisito para PCA e KMeans, além de evitar distorções nas medidas de distância.  
Em seguida, foram verificadas estatísticas básicas (média e desvio padrão) e o formato final da base para confirmar a preparação correta.

"""

categorical_cols = ['canal_preferido','categoria_favorita','regiao','pagamento','genero','faixa_etaria']
numeric_cols = ['ticket_medio','qtd_itens','idade','frequencia_compra_ord']

df_ready = pd.get_dummies(df[categorical_cols + numeric_cols], columns=categorical_cols, drop_first=False)


# Verificar estatísticas após padronização (deve ter média ~0 e desvio ~1)
df_ready[numeric_cols].describe().loc[['mean','std']]

print(df_ready.shape)
df_ready.head()

"""## 🔹 Padronização e Redução de Dimensionalidade

Os dados foram padronizados com `StandardScaler` para garantir que todas as variáveis tenham a mesma escala.  
Em seguida, aplicou-se PCA para reduzir a dimensionalidade, mantendo no mínimo **85% da variância explicada**.  
Isso elimina ruídos, reduz a complexidade do espaço e preserva as informações mais relevantes para a clusterização.

"""

scaler = StandardScaler()
X_scaled = scaler.fit_transform(df_ready)

pca = PCA(n_components=0.85, svd_solver='full', random_state=42)
X_pca = pca.fit_transform(X_scaled)

print("Componentes selecionados:", pca.n_components_)
print("Variância explicada acumulada:", pca.explained_variance_ratio_.sum().round(2))

"""## 🔹 Definição do Número de Clusters

Para escolher o número ideal de clusters, foram aplicadas duas abordagens:

- **Silhouette Score**: mede a separação e coesão dos grupos (quanto maior, melhor).  
- **Método do Cotovelo (Inércia)**: identifica o ponto onde o ganho marginal de variância explicada diminui.  

"""

sil_scores = []
inertias = []
K_range = range(2, 9)

for k in K_range:
    km = KMeans(n_clusters=k, random_state=42, n_init=10)
    labels = km.fit_predict(X_pca)

    sil = silhouette_score(X_pca, labels)

    sil_scores.append(sil)
    inertias.append(km.inertia_)

# --- Plot Silhouette ---
plt.figure(figsize=(6,4))
plt.plot(K_range, sil_scores, marker='o')
plt.title("Silhouette Score por K")
plt.xlabel("Número de Clusters (K)")
plt.ylabel("Silhouette")
plt.show()

# --- Plot método do cotovelo (Inércia) ---
plt.figure(figsize=(6,4))
plt.plot(K_range, inertias, marker='o')
plt.title("Método do Cotovelo (Inércia)")
plt.xlabel("Número de Clusters (K)")
plt.ylabel("Inércia (distância intra-cluster)")
plt.show()

"""## 🔹 Clusterização Final - Kmeans


O KMeans define centróides, mede distâncias e agrupa. Isso facilita explicar o racional das relações entre as variaveis *

**DBSCAN:** ótimo para ruídos, mas exige calibração de parâmetros (epsilon e min_samples) que poderia complicar o exercício.

**Agglomerative/Hierárquico:** útil para dendrogramas, mas menos escalável e mais difícil de explicar.

**GMM:** mais flexível que KMeans, mas adiciona complexidade estatística (probabilidades e elipses) sem necessidade para este case.


*A baixa silhueta geral diz que os segmentos de clientes não estão fortemente separados – houve muita sobreposição entre clusters até acertar as variaveis. Isso corrobora a impressão inicial de que não existem grupos óbvios extremamente diferenciados neste dataset; em vez disso, a segmentação identificada é sutil, baseada em combinações de pequenas diferenças nas muitas variáveis.*
"""

# Treinar KMeans com K=4 (config do resultado que você quer reproduzir)
k = 4
kmeans = KMeans(n_clusters=k, random_state=42, n_init=10)
labels = kmeans.fit_predict(X_pca)

print("Tamanho dos clusters:\n", sizes)

# Plot 2 PCs
plt.figure(figsize=(6,4))
sns.scatterplot(x=X_pca[:,0], y=X_pca[:,1], hue=labels, palette='viridis', s=20)
plt.title(f'KMeans (K={k})')
plt.xlabel('PC1'); plt.ylabel('PC2')
plt.legend(title="Cluster", bbox_to_anchor=(1.02,1), loc="upper left")
plt.show()

"""## 🔹 Perfil Detalhado dos Clusters

Após a clusterização, foi construído o perfil de cada grupo de clientes a partir da própria base usada no modelo.  
O resumo inclui:

- **Estatísticas numéricas**: idade média, ticket médio e quantidade média de itens por compra.  
- **Características categóricas dominantes**: canal de compra, categoria favorita, região, forma de pagamento, gênero e faixa etária mais frequentes (com percentual de representatividade).  

Esse diagnóstico permite interpretar cada cluster como um segmento de clientes com comportamentos distintos, servindo de base para recomendações de negócio.

"""

# ===== PERFIL DETALHADO usando df_used (mesma base e mesmas labels) =====
print("\nPERFIL DETALHADO DE CADA CLUSTER")
print("=================================")

cat_cols_profile = [c for c in ['canal_preferido','categoria_favorita','regiao','pagamento','genero','faixa_etaria'] if c in df_used.columns]
num_cols_profile = [c for c in ['idade','ticket_medio','qtd_itens'] if c in df_used.columns]

for c_id in sorted(df_used['cluster'].unique()):
    cluster_data = df_used[df_used['cluster'] == c_id]
    print(f"\n{'='*50}")
    print(f"CLUSTER {c_id} (Tamanho: {len(cluster_data)} clientes)")
    print(f"{'='*50}")

    # estatísticas numéricas
    for col in num_cols_profile:
        print(f"• {col}: {cluster_data[col].mean():.2f}")

    # modas categóricas (valor + %)
    print("\nCARACTERÍSTICAS CATEGÓRICAS MAIS FREQUENTES:")
    for var in cat_cols_profile:
        moda = cluster_data[var].mode()
        if not moda.empty:
            val = moda.iloc[0]
            pct = (cluster_data[var].eq(val).mean()*100)
            print(f"• {var}: {val} ({pct:.1f}%)")